<div class="container mt-4">
    <h6 class="text-start text-secondary mb-3">Status der Echtzeitdaten</h6>
    <div class="text-start">
        Zeitraum vorhandender Echtzeitdaten: <?=date("d.m.Y H:i:s", strtotime($realtimeEnergyStats->getFirstRowDate()))?> bis <?=date("d.m.Y H:i:s", strtotime($realtimeEnergyStats->getLastRowDate()))?>
    </div>
    <br>
    <h6 class="text-start text-secondary mb-3">Status der automatischen Jobs</h6>
    <table class="table table-sm table-bordered table-hover">
    <? foreach (KeyValueStoreScopeEnum::cases() as $scope) { ?>    
        <tr>
            <th class="text-start table-secondary" colspan="4"><h6><?=HtmlHelper::getDisplayNameForKVSScope($scope)?></h6></th>
        </tr>
        <? foreach ($kvsRowsPerScope[$scope->value] as $row) { 
            $notice = $row->getNotice();
        ?>
            <tr class="<?=$row->getValue() == StatusEnum::Success->value ? "table-light" : "table-danger"?>">
                <td class="text-start w-25"><?=HtmlHelper::getDisplayNameForKVSKey($row->getStoreKey())?></td>
                <td class="text-start w-auto"><?=HtmlHelper::getDisplayNameForStatus($row->getValue())?></td>                
                <td class="text-end w-25"><?=TimeHelper::formatDateTime($row->getInsertedOrUpdated(), true)?></td>
            </tr>
            <? if ($notice != "") { ?>
            <tr class="<?=$row->getValue() == StatusEnum::Success->value ? "table-light" : "table-danger"?>">
                <td></td>
                <td class="text-start" colspan="2">
                    <?=mb_substr($notice, 0, 24)?>
                    <? if (mb_strlen($notice) > 23) { ?>
                    <i class="bi bi-info-circle text-primary d-xs-inline-block d-sm-none" data-bs-toggle="tooltip" data-bs-html="true" title="<?=mb_substr($notice, 24)?>"></i><span class="d-none d-sm-inline-block"><?=mb_substr($notice, 24)?></span>
                    <? } ?>
                </td>
            </tr>
            <? } ?>
        <?} ?>        
    <?} ?>
    </table>
</div>
