<div class="container mt-4">
    <h6 class="text-start text-secondary mb-3">Status der automatischen Jobs</h6>
    <table class="table table-sm table-bordered table-hover">
    <?php foreach (KeyValueStoreScopeEnum::cases() as $scope) { ?>    
        <tr>
            <th class="text-start table-secondary" colspan="4"><h6><?=HtmlHelper::getDisplayNameForKVSScope($scope)?></h6></th>
        </tr>
        <?php foreach ($kvsRowsPerScope[$scope->value] as $row) { 
            $notice = $row->getNotice();
        ?>
            <tr class="<?=StatusEnum::isErrorOrExceptionValue($row->getValue()) ? "table-danger" : "table-light"?>">
                <td class="text-start w-25"><?=HtmlHelper::getDisplayNameForKVSKey($row->getStoreKey())?></td>
                <td class="text-start w-auto"><?=HtmlHelper::getDisplayNameForStatus($row->getValue())?></td>                
                <td class="text-end w-25"><?=TimeHelper::formatDateTime($row->getInsertedOrUpdated(), true)?></td>
            </tr>
            <?php if ($notice != "") { ?>
            <tr class="<?=StatusEnum::isErrorOrExceptionValue($row->getValue()) ? "table-danger" : "table-light"?>">
                <td></td>
                <td class="text-start" colspan="2">
                    <?php if (mb_strlen($notice) > 23) {                  
                        $shortNotice = mb_strlen($notice) > 24 ? mb_substr($notice, 24) : $notice;
                    ?>
                        <?=mb_substr($notice, 0, 24)?><i class="bi bi-info-circle text-primary d-inline-block d-sm-none" 
                            data-bs-toggle="tooltip" 
                            data-bs-html="true" 
                            title="<?= htmlspecialchars($shortNotice, ENT_QUOTES, 'UTF-8') ?>">
                        </i><span class="d-none d-sm-inline-block"><?= htmlspecialchars($shortNotice, ENT_QUOTES, 'UTF-8') ?></span>
                    <?php } else { ?>
                        <?=$notice?>
                    <?php }  ?>
                </td>
            </tr>
            <? } ?>
        <?} ?>        
    <?} ?>
    </table>
</div>
