<table class="table table-sm w-100">
    <tbody>
        <!-- Header -->
        <tr class="table-light">
        <td class="small">
                <div class="small" style="text-align: left;"><strong><span class="d-none d-sm-inline">Einkauf</span> < <?=$actualConfig->getLine1()?> W: </strong>
                <?php $textLine1 = "Einkauf < {$actualConfig->getLine1()} W: ".HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyUnderX1()) ?>
                <?php $textLine1 .= "<br> Einkauf > {$actualConfig->getLine1()} W: ".HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyOverX1()) ?>
                <?php $textLine1 .= "<br> Einkauf {$actualConfig->getLine1()} bis {$actualConfig->getLine2()} W: ".HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyBetweenX1AndX2()) ?>
                <?php $textLine1 .= "<br class='small'>(Nur der Anteil über bzw. unter {$actualConfig->getLine1()} W.)";?>
                <i class="bi bi-info-circle text-primary" data-bs-toggle="tooltip" data-bs-html="true" title="<?=$textLine1?>"></i><div>
            </td>
            <td class="small">
                <div class="small" style="text-align: left;"><strong><span class="d-none d-sm-inline">Einkauf</span> > <?=$actualConfig->getLine2()?> W: </strong>
                <?php $textLine2 = "Einkauf < {$actualConfig->getLine2()} W: ".HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyUnderX2()) ?>
                <?php $textLine2 .= "<br>Einkauf > {$actualConfig->getLine2()} W: ".HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyOverX2()) ?>
                <?php $textLine2 .= "<br> Einkauf {$actualConfig->getLine1()} bis {$actualConfig->getLine2()} W: ".HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyBetweenX1AndX2()) ?>
                <?php $textLine2 .= "<br class='small'>(Nur der Anteil über bzw. unter {$actualConfig->getLine2()} W.)";?>
                <i class="bi bi-info-circle text-primary" data-bs-toggle="tooltip" data-bs-html="true" title="<?=$textLine2?>"></i><div>
            </td>
            <td class="small">
                <div class="small" style="text-align: left;"><strong><span class="d-none d-sm-inline">Einkauf</span> > 0: </strong>
                <?php $textEm = "Einspeisung (< 0W): ".HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyUnderZero()) ?>
                <?php $textEm .= "<br>Einkauf (> 0 W): ".HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyOverZero()) ?>
                <i class="bi bi-info-circle text-primary" data-bs-toggle="tooltip" data-bs-html="true" title="<?=$textEm?>"></i><div>
            </td>
            <td class="small">
                <div class="small" style="text-align: left;"><strong>Ertrag: <strong><div>
            </td>
        </tr>
        <tr class="table-light">
            <td class="small">
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyUnderX1())?><div>
            </td>
            <td class="small">
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyOverX2())?><div>
            </td>
            <td class="small">
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($energyData->getEnergyOverZero())?><div>
            </td>
            <td class="small">
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($energyData->getSavings())?><div>
            </td>
        </tr>
    </tbody>
</table>
