<table class="table-primary">
<?php if ($energyData->getMissingRows()->isEmAvailable()) { ?>
    <tr>
        <td style="text-align: left;"><?=HtmlHelper::formatFailureValue("EM&nbsp;&nbsp;", $energyData->getMissingRows()->getEmMissingRows(), $energyData->getMissingRows()->getCountRows())?></td>
    </tr>
<?php } ?>
<?php if ($energyData->getMissingRows()->isPm1Available()) { ?>
    <tr>
        <td style="text-align: left;"><?=HtmlHelper::formatFailureValue("PM1", $energyData->getMissingRows()->getPm1MissingRows(), $energyData->getMissingRows()->getCountRows())?></td>
    </tr>
<?php } ?>
<?php if ($energyData->getMissingRows()->isPm2Available()) { ?>
    <tr>
        <td style="text-align: left;"><?=HtmlHelper::formatFailureValue("PM2", $energyData->getMissingRows()->getPm2MissingRows(), $energyData->getMissingRows()->getCountRows())?></td>
    </tr>
<?php } ?>
<?php if ($energyData->getMissingRows()->isPm3Available()) { ?>
    <tr>
        <td style="text-align: left;"><?=HtmlHelper::formatFailureValue("PM3", $energyData->getMissingRows()->getPm3MissingRows(), $energyData->getMissingRows()->getCountRows())?></td>
    </tr>
<?php } ?>
    <tr>
        <td style="text-align: left;">
            <div class="small m-0" style="color: <?= $energyData->getMissingRows()->getCountRows() > 0 ? "green" : "red"?>;">
                <?= StringHelper::formatNumber($energyData->getMissingRows()->getCountRows()) ?> Zeilen
                <?php 
                    $tooltipText = StringHelper::formatNumber($energyData->getMissingRows()->getCountRows())." Zeile für die Auswahl durchsucht, <br>".
                    StringHelper::formatNumber($realTimeEnergyDataTbl->getStatistics(true)->getTotalRows())." Zeilen in der Echtzeit-Datenbank seit <br>"
                    .TimeHelper::formatDate($realTimeEnergyDataTbl->getStatistics(true)->getFirstRowDate())
                    ." bis ".TimeHelper::formatDate($realTimeEnergyDataTbl->getStatistics(true)->getLastRowDate()).".";
                ?>
                <i class="bi bi-info-circle text-primary" data-bs-html="true" data-bs-toggle="tooltip" data-bs-placement="top" title="<?=$tooltipText?>"></i>
            </div>
        </td>
    </tr>
</table>
