            <input type="hidden" name="chartOrTableView" id="chartOrTableView" value="<?=$actualConfig->getChartOrTableViewAsString()?>">
            <input type="hidden" name="tableEnergyShowProductionTotal" id="tableEnergyShowProductionTotal" value="<?=$tableEnergyShowProductionTotal?>">

            <input type="hidden" id="energy1_chartShowEnergyOverZero" name="energy1_chartShowEnergyOverZero" value="<?=$actualConfig->configEnergy1()->getChartShowEnergyOverZero()?>">
            <input type="hidden" id="energy1_chartShowEnergyOverZeroPlusSavings" name="energy1_chartShowEnergyOverZeroPlusSavings" value="<?=$actualConfig->configEnergy1()->getChartShowEnergyOverZeroPlusSavings()?>">
            <input type="hidden" id="energy1_chartShowFeedIn" name="energy1_chartShowFeedIn" value="<?=$actualConfig->configEnergy1()->getChartShowFeedIn()?>">
            <input type="hidden" id="energy1_chartShowSavings" name="energy1_chartShowSavings" value="<?=$actualConfig->configEnergy1()->getChartShowSavings()?>">
            <input type="hidden" id="energy1_chartShowAutarky" name="energy1_chartShowAutarky" value="<?=$actualConfig->configEnergy1()->getChartShowAutarky()?>">
            <input type="hidden" id="energy1_tableShowProductionInTotal" name="energy1_tableShowProductionInTotal" value="<?=$actualConfig->configEnergy1()->getTableShowProductionInTotal()?>">
            <input type="hidden" id="energy1_tablePageLength" name="energy1_tablePageLength" value="<?=$actualConfig->configEnergy1()->getTablePageLength()?>">

            <input type="hidden" id="energy2_chartShowEnergyOverZero" name="energy2_chartShowEnergyOverZero" value="<?=$actualConfig->configEnergy2()->getChartShowEnergyOverZero()?>">
            <input type="hidden" id="energy2_chartShowEnergyOverZeroPlusSavings" name="energy2_chartShowEnergyOverZeroPlusSavings" value="<?=$actualConfig->configEnergy2()->getChartShowEnergyOverZeroPlusSavings()?>">
            <input type="hidden" id="energy2_chartShowFeedIn" name="energy2_chartShowFeedIn" value="<?=$actualConfig->configEnergy2()->getChartShowFeedIn()?>">
            <input type="hidden" id="energy2_chartShowSavings" name="energy2_chartShowSavings" value="<?=$actualConfig->configEnergy2()->getChartShowSavings()?>">
            <input type="hidden" id="energy2_chartShowAutarky" name="energy2_chartShowAutarky" value="<?=$actualConfig->configEnergy2()->getChartShowAutarky()?>">
            <input type="hidden" id="energy2_tableShowProductionInTotal" name="energy2_tableShowProductionInTotal" value="<?=$actualConfig->configEnergy2()->getTableShowProductionInTotal()?>">
            <input type="hidden" id="energy2_tablePageLength" name="energy2_tablePageLength" value="<?=$actualConfig->configEnergy2()->getTablePageLength()?>">
