<table class="table table-sm w-auto">
    <tbody>
        <tr class="table-primary">
            <td><div class="small fw-bold" style="text-align: left; width: 150px;"><?=$tableMainCaptionTimeUnit?></div></td>
            <td class="pe-3">
                <div class="small fw-bold" style="text-align: left; width: 130px;">Einkauf
                    <? $textTooltip = "Der Einkauf ist die Summe aller positiven Stromverbrauchswerte. "; ?>
                    <i class="bi bi-info-circle text-primary" data-bs-toggle="tooltip" data-bs-html="true" title="<?=$textTooltip?>"></i><div>
                </div>
            </td>
            <td class="pe-3">
                <div class="small fw-bold" style="text-align: left; width: 130px;">Einspeisung
                    <? $textTooltip = "Der Einspeisepreis berechnet sich aus der Summe der jeweils gültigen Einspeisepreise. "; ?>
                    <i class="bi bi-info-circle text-primary" data-bs-toggle="tooltip" data-bs-html="true" title="<?=$textTooltip?>"></i><div>
                </div>
            </td>
            <td class="pe-3">
                <div class="small fw-bold" style="text-align: left; width: 130px;">Ersparnis
                    <? $textTooltip = "Die Ersparnis ist die Summe der Stromproduktion, abzüglich der Einspeisung zum jeweiligen Zeitpunkt. "; ?>
                    <? $textTooltip .= "Der Preis für die Ersparnis berechnet sich aus der Summe der jeweils gültigen Einkauspreise. "; ?>
                    <i class="bi bi-info-circle text-primary" data-bs-toggle="tooltip" data-bs-html="true" title="<?=$textTooltip?>"></i><div>
                </div>
            </td>
            <td class="pe-3">
                <div class="small fw-bold" style="text-align: left; width: 130px;">Gesamtverbrauch</div>
            </td>
            <td class="pe-3">
                <div class="small fw-bold" style="display: flex; justify-content: space-between; align-items: center;">
                    <span style="text-align: left; width: 130px;">fehlende Werte</span>
                    <? $textTooltip = "Diese Seite zeigt soweit vorhanden die aufaddierten Echtzeitdaten, sowie die manuell eingegebenen Daten an."; ?>
                    <? $textTooltip .= "<br>Die Preise werden anhand der vorhandenen Preisdaten berechnet."; ?>
                    <i class="bi bi-info-circle text-primary" data-bs-toggle="tooltip" data-bs-html="true" title="<?=$textTooltip?>"></i>
                </div>
            </td>

        </tr>
        <tr class="table-primary">
            <td>
                <div class="small" style="text-align: left;"><?=$tableRow1CaptionTimeUnit?></div>
            </td>
            <td>
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getEMOverZeroTotal1())?></div>
            </td>
            <td>
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getEMUnderZeroTotal1())?></div>
            </td>
            <td>
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getPMSavingsTotal1(), $overviewPageService->getAutarkyInPercent1())?></div>
            </td>
            <td>
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getConsumptionTotal1())?></div>
            </td>
            <td>
                <a href="#" class="btn btn-sm btn-mising-values btn-<?=HtmlHelper::prepareFailureStyle($overviewPageService->getMissingValues1()->getWorstMissingRowCountPercent())?>" data-bs-toggle="popover" data-bs-content="#missingValuesTable1">
                    <?=$overviewPageService->getMissingValues1()->getWorstMissingRowCountPercent()?>%
                    <i class="bi bi-caret-down-fill"></i>
                </a>
            </td>
        </tr>
    <? if (isset($tableRow2CaptionTimeUnit)) { ?>
        <tr class="table-primary">
            <td>
                <div class="small" style="text-align: left;"><?=$tableRow2CaptionTimeUnit?></div>
            </td>
            <td>
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getEMOverZeroTotal2())?></div>
            </td>
            <td>
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getEMUnderZeroTotal2())?></div>
            </td>
            <td>
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getPMSavingsTotal2(), $overviewPageService->getAutarkyInPercent2())?></div>
            </td>
            <td>
                <div class="small" style="text-align: left;"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getConsumptionTotal2())?></div>
            </td>
            <td>
                <a href="#" class="btn btn-sm btn-mising-values btn-<?=HtmlHelper::prepareFailureStyle($overviewPageService->getMissingValues2()->getWorstMissingRowCountPercent())?>" data-bs-toggle="popover" data-bs-content="#missingValuesTable2">
                    <?=$overviewPageService->getMissingValues2()->getWorstMissingRowCountPercent()?>%
                    <i class="bi bi-caret-down-fill"></i>
                </a>
            </td>
        </tr>
    <? } ?>
    </tbody>
</table>

<!-- Popover content for missing values 1+2 -->
<div id="missingValuesTable1" class="hidden-html">
    <?php $missingValues1 = $overviewPageService->getMissingValues1()?>
    <div class="popover-heading"><strong>Fehlende Werte</strong></div>
    
    <div class="popover-body">
        <?php if ($missingValues1->isEmAvailable()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("EM", $missingValues1->getEmMissingRows(), $missingValues1->getEmMissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues1->isPm1Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM1", $missingValues1->getPm1MissingRows(), $missingValues1->getPm1MissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues1->isPm2Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM2", $missingValues1->getPm2MissingRows(), $missingValues1->getPm2MissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues1->isPm3Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM3", $missingValues1->getPm3MissingRows(), $missingValues1->getPm3MissingRowsPercent()) ?>
            </div>
        <?php } ?>
    </div>
</div>

<div id="missingValuesTable2" class="hidden-html">
    <?php $missingValues2 = $overviewPageService->getMissingValues2()?>
    <div class="popover-heading"><strong>Fehlende Werte</strong></div>
    
    <div class="popover-body">
        <?php if ($missingValues2->isEmAvailable()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("EM", $missingValues2->getEmMissingRows(), $missingValues2->getEmMissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues2->isPm1Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM1", $missingValues2->getPm1MissingRows(), $missingValues2->getPm1MissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues2->isPm2Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM2", $missingValues2->getPm2MissingRows(), $missingValues2->getPm2MissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues2->isPm3Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM3", $missingValues2->getPm3MissingRows(), $missingValues2->getPm3MissingRowsPercent()) ?>
            </div>
        <?php } ?>
    </div>
</div>
