<div class="row justify-content-center">
<table class="table table-sm w-auto summary-table">
    <tbody>
        <!-- Header -->
        <tr class="table-secondary">
            <td>
                <div class="small fw-bold"><?=$tableMainCaptionTimeUnit?></div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small fw-bold">Einkauf</div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small fw-bold">Einspeisung</div>
            </td>
            <td>
                <div class="small fw-bold">Ersparnis</div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small fw-bold">Gesamtverbrauch</div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small fw-bold">Fehlende Werte</div>
            </td>
        </tr>

        <!-- Row 1 -->
        <tr class="table-light">
            <td>
                <div class="small"><?=$tableRow1CaptionTimeUnit?></div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getEMOverZeroTotal1())?></div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getEMUnderZeroTotal1())?></div>
            </td>
            <td>
                <div class="small"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getPMSavingsTotal1(), $overviewPageService->getAutarkyInPercent1())?></div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getConsumptionTotal1())?></div>
            </td>
            <td class="d-none d-md-table-cell">
                <a href="#" class="btn btn-sm btn-mising-values btn-<?=HtmlHelper::prepareFailureStyle($overviewPageService->getMissingValues1()->getWorstMissingRowCountPercent())?>" data-bs-toggle="popover" data-bs-content="#missingValuesTable1" data-bs-trigger="focus">
                    <?=$overviewPageService->getMissingValues1()->getWorstMissingRowCountPercent()?>%
                    <i class="bi bi-caret-down-fill"></i>
                </a>
            </td>
        </tr>

        <?php if (isset($tableRow2CaptionTimeUnit)) { ?>
        <!-- Row 2 -->
        <tr class="table-light">
            <td>
                <div class="small"><?=$tableRow2CaptionTimeUnit?></div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getEMOverZeroTotal2())?></div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getEMUnderZeroTotal2())?></div>
            </td>
            <td>
                <div class="small"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getPMSavingsTotal2(), $overviewPageService->getAutarkyInPercent2())?></div>
            </td>
            <td class="d-none d-md-table-cell">
                <div class="small"><?=HtmlHelper::formatEnergyInWattAndCurrency($overviewPageService->getConsumptionTotal2())?></div>
            </td>
            <td class="d-none d-md-table-cell">
                <a href="#" class="btn btn-sm btn-mising-values btn-<?=HtmlHelper::prepareFailureStyle($overviewPageService->getMissingValues2()->getWorstMissingRowCountPercent())?>" data-bs-toggle="popover" data-bs-content="#missingValuesTable2" data-bs-trigger="focus">
                    <?=$overviewPageService->getMissingValues2()->getWorstMissingRowCountPercent()?>%
                    <i class="bi bi-caret-down-fill"></i>
                </a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
</div>

<!-- Popover content for missing values 1+2 -->
<div id="missingValuesTable1" class="hidden-html">
    <?php $missingValues1 = $overviewPageService->getMissingValues1()?>
    <div class="popover-heading"><strong>Fehlende Werte</strong></div>
    
    <div class="popover-body">
        <?php if ($missingValues1->isEmAvailable()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("EM", $missingValues1->getEmMissingRows(), $missingValues1->getEmMissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues1->isPm1Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM1", $missingValues1->getPm1MissingRows(), $missingValues1->getPm1MissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues1->isPm2Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM2", $missingValues1->getPm2MissingRows(), $missingValues1->getPm2MissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues1->isPm3Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM3", $missingValues1->getPm3MissingRows(), $missingValues1->getPm3MissingRowsPercent()) ?>
            </div>
        <?php } ?>
    </div>
</div>

<div id="missingValuesTable2" class="hidden-html">
    <?php $missingValues2 = $overviewPageService->getMissingValues2()?>
    <div class="popover-heading"><strong>Fehlende Werte</strong></div>
    
    <div class="popover-body">
        <?php if ($missingValues2->isEmAvailable()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("EM", $missingValues2->getEmMissingRows(), $missingValues2->getEmMissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues2->isPm1Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM1", $missingValues2->getPm1MissingRows(), $missingValues2->getPm1MissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues2->isPm2Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM2", $missingValues2->getPm2MissingRows(), $missingValues2->getPm2MissingRowsPercent()) ?>
            </div>
        <?php } ?>
        <?php if ($missingValues2->isPm3Available()) { ?>
            <div class="d-flex justify-content-between mb-2">
                <?=HtmlHelper::formatFailureForPopover("PM3", $missingValues2->getPm3MissingRows(), $missingValues2->getPm3MissingRowsPercent()) ?>
            </div>
        <?php } ?>
    </div>
</div>
