<div class="row justify-content-center">
    <!-- Energy Chart Legende -->
    <button id="legend-burger" class="btn btn-light btn-sm d-sm-none" data-bs-toggle="popover" 
        data-bs-placement="bottom" data-bs-html="true" data-bs-content="#menuContent1">        
    </button>
    <div class="custom-legend d-flex align-items-center justify-content-between p-2" id="legend-energy-chart" style="<?=HtmlHelper::getDisplayStyleVisibleOrNot($actualConfig->showEnergyChartView())?>">
        <div id="line-buttons" class="d-none d-sm-flex gap-2 mx-auto">
            <div class="legend-button chart-toggle-line" data-chart-id="energy-chart-container" data-custom-form-field-field="energy1_chartShowEnergyOverZero" data-custom-form-field-field2="energy1_chartShowEnergyOverZeroPlusSavings">
                <span class="legend-line em-over-zero-color me-0"></span><span class="legend-line add-savings-color ms-0" style="margin-left:0"></span><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configEnergy1()->getChartShowEnergyOverZero() ? '' : 'strikethrough'?>">(1) Stromeinkauf / Ersparnis</span>
            </div>        
            <div class="legend-button chart-toggle-line" data-chart-id="energy-chart-container" data-custom-form-field-field="energy1_chartShowFeedIn">
                <span class="legend-line feed-in-color"></span><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configEnergy1()->getChartShowFeedIn() ? '' : 'strikethrough'?>">(1) Netzeinspeisung</span>
            </div>        
            <div class="legend-button chart-toggle-line" data-chart-id="energy-chart-container" data-custom-form-field-field="energy1_chartShowSavings">
                <span class="legend-line savings-color"></span><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configEnergy1()->getChartShowSavings() ? '' : 'strikethrough'?>">(1) Ersparnis</span>
            </div>        
        <?php if ($overviewPageService->hasData2()) : ?>
            <div class="legend-vertical-line"></div>
            <div class="legend-button chart-toggle-line" data-chart-id="energy-chart-container" data-custom-form-field-field="energy2_chartShowEnergyOverZero" data-custom-form-field-field2="energy2_chartShowEnergyOverZeroPlusSavings">
                <span class="legend-line em-over-zero-color2 me-0"></span><span class="legend-line add-savings-color2 ms-0"></span><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configEnergy2()->getChartShowEnergyOverZero() ? '' : 'strikethrough'?>">(2) Stromeinkauf / Ersparnis</span>
            </div>        
            <div class="legend-button chart-toggle-line" data-chart-id="energy-chart-container" data-custom-form-field-field="energy2_chartShowFeedIn">
                <span class="legend-line feed-in-color2"></span><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configEnergy2()->getChartShowFeedIn() ? '' : 'strikethrough'?>">(2) Netzeinspeisung</span>
            </div>        
            <div class="legend-button chart-toggle-line" data-chart-id="energy-chart-container" data-custom-form-field-field="energy2_chartShowSavings">
                <span class="legend-line savings-color2"></span><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configEnergy2()->getChartShowSavings() ? '' : 'strikethrough'?>">(2) Ersparnis</span>
            </div>
        <?php endif ?>        
        </div>
    </div>
        
    <div class="custom-legend d-flex align-items-center justify-content-between p-2 w-100" id="legend-autarky-chart" style="<?=HtmlHelper::getDisplayStyleVisibleOrNot($actualConfig->showAutarkyChartView())?>">
        <div id="line-buttons" class="d-none d-sm-flex gap-2 mx-auto">
            <div class="legend-button chart-toggle-line" data-chart-id="autarky-chart-container" data-custom-form-field-field="energy1_chartShowAutarky">
                <span class="legend-line autarky-color"></span><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configEnergy1()->getChartShowAutarky() ? '' : 'strikethrough'?>">(1) Anteil selbst produzierter Strom</span>
            </div>        
            <?php if ($overviewPageService->hasData2()) : ?>
            <div class="legend-vertical-line"></div>
            <div class="legend-button chart-toggle-line" data-chart-id="autarky-chart-container" data-custom-form-field-field="energy2_chartShowAutarky">
                <span class="legend-line autarky-color2"></span><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configEnergy2()->getChartShowAutarky() ? '' : 'strikethrough'?>">(2) Anteil selbst produzierter Strom</span>
            </div>        
            <?php endif ?>        
        </div>
    </div>
    <div id="chart-buttons" class="d-flex gap-2 w-auto">
        <button class="btn btn-light btn-sm switch-chart" data-chart="EnergyChart" id="legendBtnEnergyChart" style="<?=HtmlHelper::getDisplayStyleVisibleOrNot(!$actualConfig->showEnergyChartView())?>">Energiechart</button>
        <button class="btn btn-light btn-sm switch-chart" data-chart="EnergyTable" id="legendBtnEnergyTable" style="<?=HtmlHelper::getDisplayStyleVisibleOrNot(!$actualConfig->showEnergyTableView())?>">Energietabelle</button>
        <button class="btn btn-light btn-sm switch-chart" data-chart="AutarkyChart" id="legendBtnAutarkyChart" style="<?=HtmlHelper::getDisplayStyleVisibleOrNot(!$actualConfig->showAutarkyChartView())?>">Autarkiechart</button>
    </div>
</div>

<div class="row justify-content-center">
    <!-- Energy Chart Container -->
    <div id="energy-chart-container" 
         style="<?=HtmlHelper::getDisplayStyleVisibleOrNot($actualConfig->showEnergyChartView())?>">
        <canvas id="energyChart"></canvas>
    </div>

    <!-- Autarky Chart Container -->
    <div id="autarky-chart-container" 
         style="<?=HtmlHelper::getDisplayStyleVisibleOrNot($actualConfig->showAutarkyChartView())?>">
        <canvas id="autarkyChart"></canvas>
    </div>

    <!-- Table Container -->
    <div id="energy-table-container" class="container mt-3" 
        style="<?=HtmlHelper::getDisplayStyleVisibleOrNot($actualConfig->showEnergyTableView())?>">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h6 class="text-start text-secondary m-0 d-none d-sm-block"><?=$energyTableCaption?></h6>
        </div>
        <?php include_once("energy-table.phtml");?>
    </div>
</div>
