<div class="row justify-content-center p-0 m-0 m-sm-0 m-md-0 m-xl-2 m-xxl-4">    
    <table class="table table-borderless p-0 mb-2 ms-auto">
        <tr>
            <td class="fixed-width p-0 m-0">
                <nav class="navbar navbar-expand-sm navbar-light bg-light d-sm-none p-0 nav-burger-menu">
                    
                    <!-- Burger-Icon -->
                    <button class="navbar-toggler legend-navbar-toggler p-0" type="button" data-bs-toggle="collapse" data-bs-target="#legendNavbarContent">
                        <span class="navbar-toggler-icon legend-navbar-toggler-icon"></span>
                    </button>

                    <!-- Menu content -->
                    <div class="collapse navbar-collapse" id="legendNavbarContent">
                        <!-- Realtime Chart Legend -->
                        <table class="table mb-0 text-start toggle-realtime-chart-legend-buttons">
                            <tr class="nav-item chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowEM">
                                <td><span class="legend-line em-color me-0"></span></td>
                                <td><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowEM() ? '' : 'strikethrough'?>">EM</span></td>
                            </tr>
                            <tr class="nav-item chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowPMTotal">
                                <td><span class="legend-line pm-total-color"></span></td>
                                <td><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowPMTotal() ? '' : 'strikethrough'?>">PM</span></td>
                            </tr>
                            <tr class="nav-item chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowPM1">
                                <td><span class="legend-line pm1-color"></span></td>
                                <td><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowPM1() ? '' : 'strikethrough'?>">PM1</span></td>
                            </tr>
                            <tr class="nav-item chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowPM2">
                                <td><span class="legend-line pm2-color"></span></td>
                                <td><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowPM2() ? '' : 'strikethrough'?>">PM2</span></td>
                            </tr>
                            <tr class="nav-item chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowPM3">
                                <td><span class="legend-line pm3-color"></span></td>
                                <td><span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowPM3() ? '' : 'strikethrough'?>">PM3</span></td>
                            </tr>
                        </table>
                    </div>
                
                </nav>
            </td>
            <td class="no-wrap text-center p-0 m-0 d-none d-sm-table-cell">
                <!-- Realtime Chart Legend -->                
                <div class="flex-container toggle-realtime-chart-legend-buttons ms-5">
                <span class="m-5"></span>
                    <span class="chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowEM">
                        <span class="legend-line em-color me-0"></span>
                        <span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowEM() ? '' : 'strikethrough'?>">EM</span>
                    </span>
                    <span class="chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowPMTotal">
                        <span class="legend-line pm-total-color me-0"></span>
                        <span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowPMTotal() ? '' : 'strikethrough'?>">PM</span>
                    </span>
                    <span class="chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowPM1">                    
                        <span class="legend-line pm1-color me-0"></span>
                        <span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowPM1() ? '' : 'strikethrough'?>">PM1</span>
                    </span>
                    <span class="chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowPM2">
                        <span class="legend-line pm2-color me-0"></span>
                        <span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowPM2() ? '' : 'strikethrough'?>">PM2</span>
                    </span>
                    <span class="chart-toggle-line legend-label" data-chart-id="realtime-chart-container" data-custom-form-field-field="realtime_chartShowPM3">
                        <span class="legend-line pm3-color me-0"></span>
                        <span class="legend-label flex-wrap: nowrap <?=$actualConfig->configRealtime()->getChartShowPM3() ? '' : 'strikethrough'?>">PM3</span>
                    </span>
                </div>
            </td>
            <td class="fixed-width p-0 m-0 text-end">
                <a href="#" class="btn btn-sm btn-mising-values btn-<?=HtmlHelper::prepareFailureStyle($energyData->getMissingRows()->getWorstMissingRowCountPercent())?>" data-bs-toggle="popover" data-bs-content="#missingRowSetTable" data-bs-trigger="focus">
                    <span class="d-none d-sm-inline"><?=$energyData->getMissingRows()->getWorstMissingRowCountPercent()?>%</span>
                    <i class="bi bi-caret-down-fill"></i>
                </a>
            </td>
        </tr>
    </table>
</div>

<!-- Popover content for missing values 1+2 -->
<?=HtmlHelper::renderPopoverFailureTemplate($energyData->getMissingRows(), "missingRowSetTable");?>

<div class="row justify-content-center">
    <div id="realtime-chart-container">
        <canvas id="realtimeChart"></canvas>
    </div>
</div>
