<table class="table table-bordered table-hover display responsive nowrap" id="energyTable">
    <thead class="thead-light">
        <tr>
            <th class="table-active timestamp">Zeitpunkt</th>
            <th class="table-active purchase" colspan=2>Einkauf</th>
            <th class="table-active feed-in" colspan=2>Einspeisung</th>                
            <th class="table-active savings" colspan=2>Ersparnis</th>
            <th class="table-active autarky">Autarkie</th>
            <th class="table-active production-caption" colspan="8">
                Produktion
                <label for="toggleProductionColumns" class="mb-0 me-2">
                <input type="checkbox" id="toggleProductionColumns" name="toggleProductionColumns" <?=$actualConfig->configEnergy1()->getTableShowProductionInTotal() ? "checked" : "" ?>>
                (Summe / Phasen einzeln)</label>
            </th>
        </tr>
        <tr>
            <th class="table-active timestamp"></th>
            <th class="table-active cell-energy purchase">Energie</th>
            <th class="table-active cell-price purchase">Preis</th>
            <th class="table-active cell-energy feed-in">Energie</th>
            <th class="table-active cell-price feed-in">Preis</th>
            <th class="table-active cell-energy savings">Energie</th>
            <th class="table-active cell-price savings">Preis</th>
            <th class="table-active cell-price autarky">%</th>
            <th class="table-active cell-energy production-pmtotal">Energie&nbsp;Total</th>
            <th class="table-active cell-price production-pmtotal">Preis</th>
            <th class="table-active cell-energy production-pm1">Energie&nbsp;PM1</th>
            <th class="table-active cell-price production-pm1">Preis</th>
            <th class="table-active cell-energy production-pm2">Energie&nbsp;PM2</th>
            <th class="table-active cell-price production-pm2">Preis</th>
            <th class="table-active cell-energy production-pm3">Energie&nbsp;PM3</th>
            <th class="table-active cell-price production-pm3">Preis</th>
        </tr>
    </thead>
    <tbody>                    
    <?php for($nt = 0; $nt < sizeof($overviewPageService->getLabelsXAxis()); $nt++) {             
        $captions = $overviewPageService->getLabelsXAxis()[$nt];
        $data1 = $overviewPageService->getData1List()->getItem($nt);                    
    ?>
        <tr>
            <td class="timestamp" data-sort="<?=$data1->getTimestampFrom()?>"><?=$captions[0]?></td>
            <td class="text-end purchase" data-sort="<?=$data1->getEnergyOverZero()->getEnergyInWatt()?>"><?=$data1->getEnergyOverZero()->getEnergyInWattFormated()?></td>
            <td class="text-end purchase" data-sort="<?=$data1->getEnergyOverZero()->getEnergyPriceInCent()?>"><?=$data1->getEnergyOverZero()->getEnergyPriceFormatted()?></td>
            <td class="text-end feed-in" data-sort="<?=$data1->getEnergyUnderZero()->getEnergyInWatt()?>"><?=$data1->getEnergyUnderZero()->getEnergyInWattFormated()?></td>
            <td class="text-end feed-in" data-sort="<?=$data1->getEnergyUnderZero()->getEnergyPriceInCent()?>"><?=$data1->getEnergyUnderZero()->getEnergyPriceFormatted()?></td>
            <td class="text-end savings" data-sort="<?=$data1->getSavings()->getEnergyInWatt()?>"><?=$data1->getSavings()->getEnergyInWattFormated()?></td>
            <td class="text-end savings" data-sort="<?=$data1->getSavings()->getEnergyPriceInCent()?>"><?=$data1->getSavings()->getEnergyPriceFormatted()?></td>
            <td class="text-end autarky" data-sort="<?=$data1->getAutarkyInPercent()?>"><?=StringHelper::formatNumber($data1->getAutarkyInPercent(), 2)?></td>

            <td class="text-end production-pmtotal" data-sort="<?=$data1->getProductionPmTotal()->getEnergyInWatt()?>"><?=$data1->getProductionPmTotal()->getEnergyInWattFormated()?></td>
            <td class="text-end production-pmtotal" data-sort="<?=$data1->getProductionPmTotal()->getEnergyPriceInCent()?>"><?=$data1->getProductionPmTotal()->getEnergyPriceFormatted()?></td>
            <td class="text-end production-pm1" data-sort="<?=$data1->getProductionPm1()->getEnergyInWatt()?>"><?=$data1->getProductionPm1()->getEnergyInWattFormated()?></td>
            <td class="text-end production-pm1" data-sort="<?=$data1->getProductionPm1()->getEnergyPriceInCent()?>"><?=$data1->getProductionPm1()->getEnergyPriceFormatted()?></td>
            <td class="text-end production-pm2" data-sort="<?=$data1->getProductionPm2()->getEnergyInWatt()?>"><?=$data1->getProductionPm2()->getEnergyInWattFormated()?></td>
            <td class="text-end production-pm2" data-sort="<?=$data1->getProductionPm2()->getEnergyPriceInCent()?>"><?=$data1->getProductionPm2()->getEnergyPriceFormatted()?></td>
            <td class="text-end production-pm3" data-sort="<?=$data1->getProductionPm3()->getEnergyInWatt()?>"><?=$data1->getProductionPm3()->getEnergyInWattFormated()?></td>
            <td class="text-end production-pm3" data-sort="<?=$data1->getProductionPm3()->getEnergyPriceInCent()?>"><?=$data1->getProductionPm3()->getEnergyPriceFormatted()?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tfoot>
        <tr>
            <td class="timestamp">Summe</td>
            <td class="text-end purchase"><?=$overviewPageService->getData1List()->getEnergyOverZeroSum()->getEnergyInWattFormated()?></td>
            <td class="text-end purchase"><?=$overviewPageService->getData1List()->getEnergyOverZeroSum()->getEnergyPriceFormatted()?></td>
            <td class="text-end feed-in"><?=$overviewPageService->getData1List()->getEnergyUnderZeroSum()->getEnergyInWattFormated()?></td>
            <td class="text-end feed-in"><?=$overviewPageService->getData1List()->getEnergyUnderZeroSum()->getEnergyPriceFormatted()?></td>
            <td class="text-end savings"><?=$overviewPageService->getData1List()->getSavingsSum()->getEnergyInWattFormated()?></td>
            <td class="text-end savings"><?=$overviewPageService->getData1List()->getSavingsSum()->getEnergyPriceFormatted()?></td>
            <td class="text-end autarky"><?=StringHelper::formatNumber($overviewPageService->getData1List()->getAutarkyInPercent(),2)?></td>            

            <td class="text-end production-pmtotal"><?=$overviewPageService->getData1List()->getProductionPmTotalSum()->getEnergyInWattFormated()?></td>
            <td class="text-end production-pmtotal"><?=$overviewPageService->getData1List()->getProductionPmTotalSum()->getEnergyPriceFormatted()?></td>
            <td class="text-end production-pm1"><?=$overviewPageService->getData1List()->getProductionPm1Sum()->getEnergyInWattFormated()?></td>
            <td class="text-end production-pm1"><?=$overviewPageService->getData1List()->getProductionPm1Sum()->getEnergyPriceFormatted()?></td>
            <td class="text-end production-pm2"><?=$overviewPageService->getData1List()->getProductionPm2Sum()->getEnergyInWattFormated()?></td>
            <td class="text-end production-pm2"><?=$overviewPageService->getData1List()->getProductionPm2Sum()->getEnergyPriceFormatted()?></td>
            <td class="text-end production-pm3"><?=$overviewPageService->getData1List()->getProductionPm3Sum()->getEnergyInWattFormated()?></td>
            <td class="text-end production-pm3"><?=$overviewPageService->getData1List()->getProductionPm3Sum()->getEnergyPriceFormatted()?></td>
        </tr>
    </tfoot>
</table>
