<?php
/*
 * This file is part of Home-Energy-Visualizer.
 *
 * Copyright (C) 2025 SvenoF54
 *
 * Energie-Visualisierer für Zuhause is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Energie-Visualisierer für Zuhause is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Energie-Visualisierer für Zuhause.  If not, see <https://www.gnu.org/licenses/>.
 */ 
?>
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$pageTitle?> | Energie-Visualisierung für zu Hause</title>
    
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="https://cdn.datatables.net/v/dt/dt-2.2.1/r-3.0.3/datatables.min.css" rel="stylesheet">

    <!-- jQuery DateTimePicker CSS -->
    <link href="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.21/jquery.datetimepicker.min.css" rel="stylesheet">

    <!-- Javascript-->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/v/dt/dt-2.2.1/r-3.0.3/datatables.min.js"></script>

    <!-- jQuery DateTimePicker JS -->
    <script src="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.21/build/jquery.datetimepicker.full.min.js"></script>
    
    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.6/dist/chart.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@3.0.1/dist/chartjs-plugin-annotation.min.js"></script>
    
    <link href="<?=URL_PREFIX.'css/allPages.css'.'?v='.time()?>" rel="stylesheet">
    <script src="<?=URL_PREFIX.'js/allPagesDocumentReady.js'.'?v='.time()?>"></script>

    <script>    
        const URL_PREFIX = <?=json_encode(URL_PREFIX)?>;
        <?php
            // Add JS-Vars
            foreach($jsVars as $key => $val) {?>
        const <?=$key?> = <?=$val?>;
        <?php  } ?>        
    </script>
        
    <?php
        // Add JS-Header-Files
        foreach($jsHeaderFiles as $file) { ?>
    <script src="<?=URL_PREFIX.$file.'?v='.time()?>"></script>
    <?php  } ?>

    <?php
        // Add CSS-Files
        foreach($cssFiles as $file) { ?>
    <link rel="stylesheet" type="text/css" href="<?=URL_PREFIX.$file.'?v='.time()?>"/>
    <?php  } ?>

</head>
<body>
    <div class="container-fluid">
        <?php include_once("views/partials/navigation.phtml")?>

        <?php if (isset($partialTop)) include($partialTop); ?>
        <?php if (isset($errorMsg) && $errorMsg != "") { ?>
            <div class="col text-center text-danger">
                <strong><?=$errorMsg?></strong>
            </div>
        <?php } ?>
        <?php if (isset($successMsg) && $successMsg != "") { ?>
            <div class="col text-center text-success">
                <strong><?=$successMsg?></strong>
            </div>
        <?php } ?>

        <?php if (isset($partialBottom)) include($partialBottom); ?>
    </div>

    <?php
        // Add JS-Footer-Files
        foreach($jsFooterFiles as $file) { ?>
    <script src="<?=URL_PREFIX.$file.'?v='.time()?>"></script>
    <?php  } ?>

</body>
</html>
